pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn clean install'
        git 'https://github.com/sragavan300/Jenkins-Zero-To-Hero/blob/feature1/multi-stage-multi-agent/App.java'
        sh 'mvn --version'
      }
    }
    stage('Run Java Program') {
            steps {
                sh 'java -version' // Display Java version
                sh 'mvn exec:java -Dexec.mainClass="com.example.HelloWorldApp"' // Run the Java program
            }
    
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
